### ISSUE TITLE
Deprecate Crate#getKeyItem

### ISSUE THREAD

**Issue by imWillX** [Hazebyte/CrateReloadedAPI#10]
https://github.com/Hazebyte/CrateReloadedAPI/blob/cc93f15781844b95d93997825a345a66c8606157/src/main/java/com/hazebyte/crate/api/crate/Crate.java#L24

**Comment by puigru** [comment]
What is the recommended replacement?

**Comment by imWillX** [comment]
Crate#getKeyItem and Crate#getCrateItem will be changed into Crate#getItem since there is won't be a difference in 2.0.0.
