### ISSUE TITLE
CrateInteractEvent fires even after PlayerInteractEvent is cancelled

### ISSUE THREAD

**Issue by puigru** [Hazebyte/CrateReloadedAPI#16]
Title.

**Comment by imWillX** [comment]
@XXLuigiMario 
Didn't notice before. PlayerInteractEvent seems to cancel events if the player interacts with air. 

MysteryCrates will violate this cancel agreement

**Comment by puigru** [comment]
Well, since https://github.com/Hazebyte/CrateReloadedAPI/issues/15 is now fixed, I don't think this will be too much of an issue. Just make sure to mention it in the documentation.
