### ISSUE TITLE
Ingame GUI editor

### ISSUE THREAD

**Issue by cdmvirt** [Hazebyte/CrateReloadedAPI#25]
Would be great to see a ingame GUI crate editor, simple and easy for admin/operators to work with. Currently using Cratesplus but your plugin is so much better.

**Comment by puigru** [comment]
I'm currently working on an in-game crate GUI crate editor, however, I can't give any ETA yet.

EDIT: I forgot to mention this won't be released until after CrateReloaded's new upcoming update, 2.0.0, as it includes required new API functionality.

**Comment by imWillX** [comment]
I'm working on this now.

Details will be posted here: https://github.com/Hazebyte/CrateReloaded/issues/10
