### ISSUE TITLE
Infinite Key Glitch

### ISSUE THREAD

**Issue by Tomographix** [Hazebyte/CrateReloadedAPI#30]
Hi,
A player today worked out how to get infinite keys if the crate has a confirmation screen enabled.

Step 1. Put key into any inventory slot from 1 - 9
Step 2. Open the crate and at the same time spam a different inventory slot to the one the key is in
For example, keys in inventory slot 1, so spam 4 on your keyboard.

This should trick the crate into not removing the key from your inventory as it believe that the new inventory slot that you have selected has it taken out.

**Comment by imWillX** [comment]
Update to the latest. 

This has been fixed.
