### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Ergenta** [Hazebyte/CrateReloadedAPI#31]
Requesting a permission for creative control limitations on crates.

**Comment by Ergenta** [comment]
These never get read, do they?

**Comment by imWillX** [comment]
[They do.](https://github.com/Hazebyte/CrateReloadedAPI/issues?q=is%3Aissue+is%3Aclosed)

This repo is for the API. Actual plugin functionality is [here](https://github.com/Hazebyte/CrateReloaded/issues).
