### ISSUE TITLE
Sounds around crates

### ISSUE THREAD

**Issue by BiGUNMAN** [Hazebyte/CrateReloadedAPI#32]
Why does CrateReloaded stop sounds from being played for over 1 second around key crates (does this have to do with persistent sounds of keycrates)?

If I do `/playsound minecraft:(sound) (player)` to a player standing beside a keycrate, the sound is canceled after 1 second (so a sound that may last 1-10 seconds just gets canceled halfway through).

This also happens to sounds that come from plugin! We use an end-sound that's about 3 seconds long, and it abruptly stops playing after 1 second (happens on all crate types)

**Comment by imWillX** [comment]
@BiGUNMAN 

What specific sound are you looking at? We set up a default pitch of 1. Perhaps that may be causing an issue? 

Try adding a pitch to the effect section and change it to 1-10.

**Comment by Sxtanna** [comment]
@imWillX I believe this has to do [MC-36952](https://bugs.mojang.com/browse/MC-36952), in which sounds are overwritten if there are many sounds being played to the client.

**Comment by imWillX** [comment]
@Sxtanna Thanks, I believe this would answer the issue for you @BiGUNMAN 

Closing
