### ISSUE TITLE
Add event CrateOpenEvent

### ISSUE THREAD

**Issue by Will33ELS** [Hazebyte/CrateReloadedAPI#34]
Hello,

After many tests, I found that the ClaimEvent vent does not detect the opening of a safe and that the event CrateInteractEvent is not suitable for what I'm looking for. I would need to vent "CrateOpenEvent" which is call when a player successfully opens a safe. My usefulness will be to display an opening message to the players having activated a preference to display the messages of openings of the coffers.

Thank you ;)

---- 

Bonjour,

Après de nombreux test, j'ai constaté que l’évent ClaimEvent ne permettez pas de détecter l'ouverture d'un coffre et que l'événement CrateInteractEvent n'est pas adapté à ce que je recherche. Il me faudrait en évent "CrateOpenEvent" qui est appeler lorsqu'un joueur ouvre avec succès un coffre. Mon utilité serai d'afficher un message d'ouverture aux joueurs ayant activé une préférence d'affichage des messages d'ouvertures des coffres.

Merci ;)

**Comment by imWillX** [comment]
Hey, 
Have you tried CrateInteractEvent and checking if the action is open? 

https://github.com/Hazebyte/CrateReloadedAPI/blob/dev/src/main/java/com/hazebyte/crate/api/crate/CrateAction.java

https://github.com/Hazebyte/CrateReloadedAPI/blob/dev/src/main/java/com/hazebyte/crate/api/event/CrateInteractEvent.java

**Comment by Will33ELS** [comment]
Hello,
no, the Open action is call even when the player does not open the chest successfully. Example: The player does not have a key in their hand, the action remains Open

---

Bonjour,
non, l'action Open est appeler meme lorsque le joueur n'ouvre pas le coffre avec succès. Exemple: Le joueur n'a pas de clé dans la main, l'action reste Open
