### ISSUE TITLE
PlaceholderAPI varaibles or CMI Hologram support.

### ISSUE THREAD

**Issue by TomLewis** [Hazebyte/CrateReloadedAPI#43]
Ahoy

I see you support Holograms plugin, but not CMI Holograms, which is the second largest hologram plugin for Spigot servers, if you created a placeholderAPI plugin then I could just add this to any existing plugin like CMI Holograms and put them above crates to show crate information above the crates.
Otherwise, could you please suppose CMI Holograms as they have an API, as I dont want to have to use 2 separate hologram plugins just to get Crate holograms working.

You could have a Hologram actually spin the items that are in a crate, so others can see when a user opens a crate and its spinning as Holograms can show items in them, with an awesome winning Hologram animation to show what they won.

**Comment by imWillX** [comment]
Hey @FrozenBeard

We'll be able to include this in 2.1.X. Could you post this in the main repo (https://github.com/Hazebyte/CrateReloaded/issues)? This repo is primarily for API.

**Comment by TomLewis** [comment]
> 
> 
> Hey @FrozenBeard
> 
> We'll be able to include this in 2.1.X. Could you post this in the main repo (https://github.com/Hazebyte/CrateReloaded/issues)? This repo is primarily for API.

Done!

https://github.com/Hazebyte/CrateReloaded/issues/451

**Comment by imWillX** [comment]
Great, thanks. Will be closing this one.
