### ISSUE TITLE
`[CrateReloaded] Uncaught exception.`

### ISSUE THREAD

**Issue by RhythmicSys** [Hazebyte/CrateReloadedAPI#64]
crate file:
https://mclo.gs/QzWxtut

Full error:
https://mclo.gs/x6VDAMa

Getting an 'uncaught exception' when trying to do `/cr reload` with this config file

Server version: `git-Purpur-1809 (MC: 1.19.2)*`

**Comment by imWillX** [comment]
Check the format of the VoteKey. 

```
item: 'display:(iron_nugget{CustomModelData:1} 1) name:&6&l[&a&nVote_Key&6&l] lore:&7Thank_you_for_voting!\|&8Right_click_the_vote_crate_to_use glow:true'
--
```
