### ISSUE TITLE
Missing advanced crate functionality: Effects, Holograms, etc..

### ISSUE THREAD

**Issue by puigru** [Hazebyte/CrateReloadedAPI#7]
Currently, the API doesn't allow you to tinker with advanced crate functionality. As I understand it, allowing such functionality to be manipulated through the API would require a lot of work. So in the meantime it would be nice to be able to modify them through some other means, even if it's by specifying arbitrarily formatted strings, which match those present in the config, as the plugin already does that internally when parsing the config.

* ~~Holograms~~ (added in 343fd06)
* ~~Effects~~ (added in 7578182)
* ~~Economy (missing Crate#setCost method)~~ (added in 3395f01)

**Comment by imWillX** [comment]
We turned to EffectLib for effects. Resultantly, the start method is using a configuration section as shown [here](https://github.com/imWillX/EffectLib/blob/59fdbfb0faaa6aec7213f305ee5773eb0b48c8a0/src/main/java/de/slikey/effectlib/EffectManager.java#L144).

I'll take any suggestions for passing this functionality to API.

**Comment by puigru** [comment]
@imWillX 
How about Crate#setEffect(EffectTag tag, String effectClass, ConfigurationSection parameters)
That or Crate#setEffect(EffectTag tag, String str) throws IllegalArgumentException
EffectTag would be an enum similar to Tag, but instead for message, for effects.
In the second, 'str' would be a String that would be parsed as if it were extracted directly from the config.

**Comment by imWillX** [comment]
Closing, I believe API functionality is added. Please reopen this issue or post another ticket if you believe there is something missing.
