### ISSUE TITLE
Make sure crates are valid before registering them

### ISSUE THREAD

**Issue by puigru** [Hazebyte/CrateReloadedAPI#8]
Crates must meet certain minimum specifications in order for the plugin to work correctly. These conditions should be checked before a crate is allowed to be registered, if a crate does not meet such conditions, instead, an IllegalArgumentException (or similar) should be thrown, preferrably specifying what conditions the crate did not meet.

**Comment by imWillX** [comment]
Minimum requirements need a valid...
```
Crate Item
Crate Name
```
